# Generated by Django 3.2.5 on 2021-09-04 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Revitex', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='slots',
        ),
    ]
