# Generated by Django 3.2.5 on 2021-09-04 12:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Revitex', '0002_delete_slots'),
    ]

    operations = [
        migrations.CreateModel(
            name='slots',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('slots_restant', models.IntegerField()),
                ('centre', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Revitex.centre')),
                ('controleTechnique', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Revitex.controle_technique')),
                ('gestionnaire', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Slots',
            },
        ),
    ]
